### ISSUE TITLE
Switch to the latest release of capstone

### ISSUE THREAD

**Issue by monkbai** [GJDuck/e9patch#10]
Old version of capstone has bugs that the `access` value of operands become zero for some instructions, as mentioned in
[https://github.com/aquynh/capstone/issues/1562#issuecomment-548952209](https://github.com/aquynh/capstone/issues/1562#issuecomment-548952209)
and
[https://github.com/aquynh/capstone/issues/1624](https://github.com/aquynh/capstone/issues/1624)

E9patch will check the access value while getOperand [https://github.com/GJDuck/e9patch/blob/d44c130fad0f01325ca9b32a0d7bb442168fa6ed/src/e9tool/e9tool.cpp#L1431](https://github.com/GJDuck/e9patch/blob/d44c130fad0f01325ca9b32a0d7bb442168fa6ed/src/e9tool/e9tool.cpp#L1431), in this case the operands are never available.

Example: 
`vfmadd213ss in, xmm2, dword ptr [r13-1Ch]`
Action:
`try to print &mem[0]`
Warning:
`warning: vfmadd213ss xmm3, xmm2, dword ptr [r13 - 0x1c]: failed to load mem[0]; index is out-of-range`

Switching to the latest capstone in `build.sh` can fix this issue (I used version 4.0.2).

**Comment by GJDuck** [comment]
The project was previously using that version, but it failed to disassemble some AVX512 instructions which meant that Chrome could not be rewritten.  For some reason, the older dev version of Captsone worked fine, hence the revert.

How about if I modify the `build.sh` script to make the Capstone version configurable?  That way, you can use 4.0.2 if it suits your application?

**Comment by monkbai** [comment]
Thank you for the prompt reply, I modified the build.sh script locally and it works well for my application, but still I think it is better to make the Capstone version configurable.
