### ISSUE TITLE
Using symbols in call actions

### ISSUE THREAD

**Issue by joshop** [GJDuck/e9patch#12]
Is it possible in any way to use symbols from a binary in the code for call actions that are used with e9tool on that binary? For example, if a C program that is being rewritten defines a function `void f()`, is there a way I can easily do `f();` in the source for a call action?

**Comment by GJDuck** [comment]
It should be possible by passing the address of `f` as a parameter, e.g.:

       e9tool ... -A 'call entry(&f, ...)@example' ...

This assumes that symbol `f` is defined in the ELF binary.

Calling `f` requires some care.  For performance reasons, call actions do not save the FPU state nor align the stack, as required by the System V ABI.  Thus, to safely call `f`, you'd need to:

- Align the stack pointer to a 16byte boundary
- Save the FPU state
- Call `f`
- Restore the FPU state
- Restore previous stack (mis)alignment

If `f` and all functions called by `f` do not affect the FPU state, then it is probably safe to call `f` directly.

Another problem is whether `f` affects any global state or attempts to acquire locks.  This can easily corrupt the program's state or cause deadlocks.
