### ISSUE TITLE
Is there a way we can match all conditional jump instructions ("je", "jne", etc) and not all jump instructions.

### ISSUE THREAD

**Issue by BharathMonash** [GJDuck/e9patch#14]
Hi, I'm looking to match all conditional jumps and instrument them. Is there a way I can match just the conditional jump statements and not all jumps statements? how can change this option `--match 'asm=j.*'` to suit the above requirement ? 

Looking forward to hearing from you. Thank for the help in advance!

**Comment by GJDuck** [comment]
One way is to change the regular expression, e.g.:

        ./e9tool -M 'asm=j[^m].*' -A print xterm

I.e., the second character must not be an "`m`", excluding `jmpq ...` etc.

Or you could do something like:

        ./e9tool -M 'jump and rflags in reads' -A print xterm

I.e., match all instructions that are (1) jumps, and (2) read the flags register.

**Comment by BharathMonash** [comment]
Thank you so much.
I was trying to regex with `||` and `&&` but ended up in `std::regex error`. This looks promising, let me give it a try :)
