### ISSUE TITLE
This warning occurs with the op[0] parameter

### ISSUE THREAD

**Issue by ClearLove27149** [GJDuck/e9patch#15]
![image](https://user-images.githubusercontent.com/63400257/118391242-debfdc80-b665-11eb-8e81-730204ed865f.png)
hello, I'm using the op[0] parameter, but this warning appears. I don't know why

**Comment by ClearLove27149** [comment]
![image](https://user-images.githubusercontent.com/63400257/118391337-5beb5180-b666-11eb-9e2b-d14309be595d.png)
mov_rule.c

**Comment by GJDuck** [comment]
Thanks for the report.  Seems to be a leftover bug from the Zydis port.  It should be fixed now.
