### ISSUE TITLE
Failed to match function calls

### ISSUE THREAD

**Issue by mirzamomen** [GJDuck/e9patch#17]
Hi. I have the following toy example (toy_example.c) in which malloc function is called.

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
   char *news = (char *)malloc(3 * sizeof(char));
   strcpy(news, "hi");
   printf("news is: %s\n", news);
   return 0;
}
`

I compiled it as:   
    gcc -o toy_example toy_example.c

I wanted to add instruction print instrumentation to the call to 'malloc' using E9tool, with the following command:

./e9tool -M 'call and imm[0] == &malloc' -A print ./toy_example

 but it fails to match the line. Is this a bug or I am missing something here?

Best regards

**Comment by mirzamomen** [comment]
Also, I need to instrument all compare statements in which some variable is being compared to a constant value. 

I tried with the following toy example:

enum week{Mon = 133, Tue, Wed};
int main() {
   enum week day = Wed;
   printf("Day is: %d\n", Mon);
   if (day == Tue) printf("It is Tuesday\n"); else printf("It is not Tuesday\n");
   return 0;
}

The following line caused 5 instrumentations, as follows:
# ./e9tool -M 'asm=cmp.* and op.size ==2' -A print ./example2
# ./a.out prints the following output:

cmp %rbx, %rbp
Day is: 133
cmpl $0x86, -0x4(%rbp)
It is not Tuesday
cmpb $0x0, 0x2009c9(%rip)
cmpq $0x0, 0x2009a7(%rip)
cmp %rdi, %rax

When I try to filter out just the comparison with the constant value 0x86 with the following command, it does not match anything.

./e9tool -M 'asm=cmp.* and op.size ==2 and op[0]==0x86' -A print ./example2

can you please advise me how to do that or where I am doing wrong?

Best regards

**Comment by GJDuck** [comment]
Thanks for the report.  Yes, it was another bug and should be fixed now.

Some kind of basic regression test suite for E9Tool is badly needed but still on the TODO list.
