### ISSUE TITLE
ELF support broken post PE integration

### ISSUE THREAD

**Issue by farimani** [GJDuck/e9patch#24]
Hi,

Last good commit hash for ELF support is 3826471993fadad92a7df821d6d6dfca9ad25ec7 ("3826471993fadad92a7df821d6d6dfca9ad25ec7") as far as I can tell.

```
#include <stdio.h>

int main()
{
    printf("hello world\n");
    return 0;
}
```

`gcc -static hello.c -o hello`

`./e9tool -O0 -M 'asm=syscall' -A print hello`

Running the output segfaults.

**Comment by GJDuck** [comment]
This example works fine on my system.  I will try a different system later today.

**Comment by GJDuck** [comment]
I fixed a bunch of compatibility issues with newer systems, so maybe it will work now.

**Comment by farimani** [comment]
working now. thanks a ton.
