### ISSUE TITLE
ELF binaries without DT_INIT

### ISSUE THREAD

**Issue by farimani** [GJDuck/e9patch#27]
Is there a workaround for ELF binaries without DT_INIT? Can one use a different tool like objcopy to add one prior to running e9patch/tool?

**Comment by GJDuck** [comment]
I think it currently assumes that `DT_INIT` exists.  This could be fixed, to use `DT_INIT_ARRAY[0]` as a backup.

If neither exist, then I am not sure.  Maybe it is possible to inject a `DT_INIT` entry by overwriting another entry that is technically redundant, such as maybe `DT_GNU_HASH`.

**Comment by GJDuck** [comment]
E9Patch will now use `DT_INIT_ARRAY[0]` if `DT_INIT` is missing.
