### ISSUE TITLE
musl patching

### ISSUE THREAD

**Issue by farimani** [GJDuck/e9patch#29]
A patched ld-musl causes a segfault when used directly by a program, and does not seem to intercept any calls when used as LD_PRELOAD.

Are there any magics to make this work?

**Comment by GJDuck** [comment]
Please tell me where to get `ld-musl` and what command you used for instrumentation.

It appears to be an `ld.so` replacement.  I'm not sure if the dynamic linker itself can be rewritten as I've never tried that.

**Comment by farimani** [comment]
My aplogies. musl is a lightweight libc implementation with libc/dl/ld all in one library:

https://musl.libc.org/

It's used in Alpine distributions, a popular base image for building containerized workloads.

If you have docker you can get a binary of the library like this:

`cd e9patch`
`docker run --rm -it -v$(pwd):/e9patch alpine sh -c 'cp /lib/ld-musl-x86_64.so.1 /e9patch/'`

Patch it (syscall):

`./e9tool -M 'asm=syscall' -A print --shared ./ld-musl-x86_64.so.1`

Run with patched library:

`docker run --rm -it -v$(pwd)/a.so:/lib/ld-musl-x86_64.so.1 alpine ls /`
`echo $?`

This returns 139 - segfault

Run it as LD_PRELOAD:

`docker run --rm -it -v$(pwd):/e9patch -e LD_PRELOAD=/e9patch/a.so alpine ls /`

The preloaded lib doesn't seem to load. I don't think musl accepts LD_DEBUG so I couldn't get more visibility into why this isn't working.

You can patch it as an executable and run the library, which then prints the right messages but that wouldn't help when used as a library:

`./e9tool -M 'asm=syscall' -A print --executable ./ld-musl-x86_64.so.1`
`./a.so`

I've tried patching ld.so and it didn't work due to lack of DT_INIT. But I believe that ld makes certain assumptions about its own arrangement in memory and it doesn't like things moved around, and perhaps the source of problem with ld-musl lib.

**Comment by GJDuck** [comment]
I think this issue was resolved, so I will close it.
