### ISSUE TITLE
what's the blocker for non-x86 binaries?

### ISSUE THREAD

**Issue by Mis012** [GJDuck/e9patch#33]
The readme says that only x86_64 binaries are supported, but doesn't list the reasoning (and doesn't even have this limitation listed under the "assumptions" section).
What is the reason for only supporting this one architecture, and is support for other architectures (arm, aarch64) planned?

**Comment by GJDuck** [comment]
The binary rewriting methodology used by E9Patch works at the x86_64 machine-code level.  The techniques could be ported to other architectures provided some properties are satisfied, such as:

1. Variable-length instructions
2. Unconditional jump instruction encoding compatible with instruction punning
3. A reasonable unconditional jump range

Most of the other popular architectures are RISC-like, and are not compatible with E9Patch-style rewriting.
