### ISSUE TITLE
Can you add stdlib support for atexit()

### ISSUE THREAD

**Issue by passthecilantro** [GJDuck/e9patch#35]
Hi,
I'm using e9patch/e9tool/e9afl to insert my own initialization function using E9Tool Plugin API specifically e9_plugin_init_v1().  My initialization function uses atexit() which allows me to add further control as to what happens when my rewritten binaries exit normally. Can you add stdlib support for atexit() in the project's stdlib.c ?

**Comment by GJDuck** [comment]
It may be possible to add this in future by redirecting `DT_FINI`/`DT_FINI_ARRAY`, but this will require some work.

In the meantime, you could create a shared object that exports a destructor using GCC's `__attribute__((destructor(N)))` syntax.  Then you can dynamically load the shared object using stdlib's `dlopen()`.  Provided the rewritten binary exits normally, the descructor should be called (untested).

**Comment by GJDuck** [comment]
There is no `atexit()` specifically, but you can now define a `fini()` function that will be called when the program exits normally.
