### ISSUE TITLE
win64_demo

### ISSUE THREAD

**Issue by ClearLove27149** [GJDuck/e9patch#36]
hello, how to use win64_demo?
![ZZP(TZLH$CO6YSELH0@PJ3D](https://user-images.githubusercontent.com/63400257/141951990-e779c223-2eb8-45bb-a788-13380049778b.png)

**Comment by GJDuck** [comment]
I've replaced the example with a valid command.

The windows port is not really tested.  Feel free to open new issues if you find other problems.
