### ISSUE TITLE
Segmentation fault upon instrumenting 'asm=ret' 

### ISSUE THREAD

**Issue by jjang3** [GJDuck/e9patch#37]
Hello!

I am doing very simple patching to test out the latest patching capability of the E9Patch version and came across this issue.

Here are the following steps to reproduce the error:

1. `git clone git@github.com:GJDuck/e9patch.git`
2. `cd e9patch && bash build.sh`
3. `./e9tool -M 'asm=ret' -P empty bzip2`
4. `truncate --size=1G test.txt && ./a.out test.txt`                                

I'm not sure if this is only the problem from my end, or maybe others have this issue as well. 

I have attached the screenshot below:
<img width="1136" alt="Screen Shot 2021-11-23 at 5 52 02 PM" src="https://user-images.githubusercontent.com/42549923/143141615-85c82f8d-6e63-438c-b5b6-491bab969c66.png">

I have also tried this on `xterm` which results in the same error.
Sincerely,

**Comment by GJDuck** [comment]
Thanks for the report.  I think it should be fixed now, otherwise please reopen.
