### ISSUE TITLE
How to patch at given address?

### ISSUE THREAD

**Issue by chamibuddhika** [GJDuck/e9patch#4]
Just read your paper. It was a nice read!

I tried instrumenting a Redis binary with `e9tool` as follows.

```
./e9tool --action='addr=0x00000000004418fb:call entry@counter' redis-server
```
where the address occurs in some malloc function.

```
Dump of assembler code for function zmalloc_get_memory_size:
   0x00000000004418f0 <+0>:	push   %rbx
   0x00000000004418f1 <+1>:	mov    $0x55,%edi
   0x00000000004418f6 <+6>:	callq  0x42f2e0 <sysconf@plt>
   0x00000000004418fb <+11>:	mov    $0x1e,%edi
   0x0000000000441900 <+16>:	mov    %rax,%rbx
   0x0000000000441903 <+19>:	callq  0x42f2e0 <sysconf@plt>
   0x0000000000441908 <+24>:	imul   %rbx,%rax
   0x000000000044190c <+28>:	pop    %rbx
   0x000000000044190d <+29>:	retq   
End of assembler dump.
```

And I got the following output from the tool.

```
+M+
[0000000000000001][F000000003FFFFFF]
Q65

-----------------------------------------------
input_binary          = redis-server
input_mode            = EXECUTABLE
num_patched           = 0 / 0 (-nan%)
num_patched_B1        = 0 / 0 (-nan%)
num_patched_B2        = 0 / 0 (-nan%)
num_patched_T1        = 0 / 0 (-nan%)
num_patched_T2        = 0 / 0 (-nan%)
num_patched_T3        = 0 / 0 (-nan%)
num_virtual_mappings  = 3
num_physical_mappings = 2 (66.67%)
num_virtual_bytes     = 12288
num_physical_bytes    = 8192 (66.67%)
input_file_size       = 9122208
output_file_size      = 9135184 (100.14%)
time_elapsed          = 5ms
```

And I don't see the output `a.out` containing the patch. Am I missing something here?

**Comment by GJDuck** [comment]
Hi, the `--action` option works by string regular-expression matching, so your string is probably not matching the string `e9tool` expects.  I think the problem is the `0`-padding, so probably the following will work:

    ./e9tool --action='addr=0x4418fb:call entry@counter' redis-server

**Comment by chamibuddhika** [comment]
Thanks. I tried that as well. The output looks better (I suppose).

```
.
+M+
[0000000000000001][F000000007FFFFFF]
Q656

-----------------------------------------------
input_binary          = redis-server
input_mode            = EXECUTABLE
num_patched           = 1 / 1 (100.00%)
num_patched_B1        = 1 / 1 (100.00%)
num_patched_B2        = 0 / 1 (0.00%)
num_patched_T1        = 0 / 1 (0.00%)
num_patched_T2        = 0 / 1 (0.00%)
num_patched_T3        = 0 / 1 (0.00%)
num_virtual_mappings  = 3
num_physical_mappings = 2 (66.67%)
num_virtual_bytes     = 12288
num_physical_bytes    = 8192 (66.67%)
input_file_size       = 9122208
output_file_size      = 9139304 (100.19%)
time_elapsed          = 5ms
-----------------------------------------------
```

But I don't see the patched in interception branch at the patch location. Any ideas?

**Comment by GJDuck** [comment]
> But I don't see the patched in interception branch at the patch location. Any ideas?

Yes, try the following:

    ./e9tool -s --action='addr=0x4418fb:call entry@counter' redis-server
    objdump -d ./a.out

The `-s` option will cause the binary code to be directly patched in the file itself.  This is opposed to the default, where the patched pages are only loaded during program initialization.  The default is more stable for binaries that use some more advanced dynamic linker features that can cause the patched code to be executed before the trampolines are loaded (resutling in a crash).

Alternatively, you can just run the patched program in a debugger.  The patched code will be visible after the program has loaded.

**Comment by chamibuddhika** [comment]
Thanks. That worked.
