### ISSUE TITLE
CFGAnalysis is removed in "e9tool.h"

### ISSUE THREAD

**Issue by spinpx** [GJDuck/e9patch#44]
Hi GJDuck, I found that e9afl used "CFGAnalysis" to find code target.
But on the newest version of e9patch, the function definition is removed. If I want to used e9afl with newest e9patch,
which function should I use? `CFGCodeAnalysis` or `buildTargets`?

Thanks.

**Comment by GJDuck** [comment]
The equivalent function will be `e9tool::buildTargets`.

I am finalizing the `e9tool` API, and then I will update `e9afl`/`e9syscall`/etc. tools after that.  It is not really critical since the older versions of `e9tool` should work fine, unless you also want to use some of the newer features.
