### ISSUE TITLE
win64_demo patched program crash

### ISSUE THREAD

**Issue by AiDaiP** [GJDuck/e9patch#46]
I run the win64_demo with your command. When I run the patched program, It always crash. 
I want to know some details about win64_demo.
Could you please upload the target program you use to test win64_demo and it's souce code and the command to compile it.
Thanks.

**Comment by GJDuck** [comment]
I have not tried the demo in a long time, so maybe something is broken.
But first can I check if you compiled it using the right ABI (`-mabi=ms`):

        ./e9compile.sh examples/win64_demo.c -mabi=ms

**Comment by AiDaiP** [comment]
```
 ./e9compile.sh examples/win64_demo.c -mabi=ms
gcc -fno-stack-protector -fpie -O2 -Wno-unused-function -mno-mmx -mno-sse -mno-avx -mno-avx2 -mno-avx512f -msoft-float -fno-tree-vectorize -fomit-frame-pointer -c -Wall -mabi=ms examples/win64_demo.c
examples/win64_demo.c:7:1: warning: multi-line comment [-Wcomment]
    7 | //  *    ./e9tool \
      | ^
examples/win64_demo.c:391:12: warning: conflicting types for built-in function ‘vfprintf’; expected ‘int(void *, const char *, char *)’ [-Wbuiltin-declaration-mismatch]
  391 | static int vfprintf(intptr_t handle, const char *format, va_list ap)
      |            ^~~~~~~~
examples/win64_demo.c:29:1: note: ‘vfprintf’ is declared in header ‘<stdio.h>’
   28 | #include "../src/e9patch/e9loader.h"
  +++ |+#include <stdio.h>
   29 |
examples/win64_demo.c:406:12: warning: conflicting types for built-in function ‘fprintf’; expected ‘int(void *, const char *, ...)’ [-Wbuiltin-declaration-mismatch]
  406 | static int fprintf(intptr_t handle, const char *format, ...)
      |            ^~~~~~~
examples/win64_demo.c:406:12: note: ‘fprintf’ is declared in header ‘<stdio.h>’
gcc win64_demo.o -o win64_demo -pie -nostdlib -Wl,-z -Wl,max-page-size=4096 -Wl,-z -Wl,norelro -Wl,-z -Wl,stack-size=0 -Wl,--export-dynamic -Wl,--entry=0x0 -Wl,--strip-all
```

**Comment by AiDaiP** [comment]
Then I run: 
```
./e9tool -M 'asm=/xor.*/' -P 'entry(config,addr,instr,size,asm)@win64_demo' fuck.exe -o patched.exe
```
After it I run the patched program patched.exe.  patched.exe will crash.

**Comment by AiDaiP** [comment]
Then I run:
```
./e9tool -M 'asm=/xor.*/' -P 'entry(config,addr,instr,size,asm)@win64_demo' prog.exe -o patched.exe
```
After it I run the patched program patched.exe. patched.exe will crash.

**Comment by AiDaiP** [comment]
```
(gdb) r
Starting program: C:\Users\AiDai\Desktop\curl_patched.exe
[New Thread 18980.0x990]
[New Thread 18980.0x3748]
[New Thread 18980.0x3478]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000014f068c38 in ?? ()
(gdb)

**Comment by GJDuck** [comment]
Type `la a` into GDB to find the crashing instruction + context.

I will try to test it myself in the next day or so.

**Comment by AiDaiP** [comment]
![1](https://user-images.githubusercontent.com/43956964/160533678-878d89ef-de7f-4c42-a0ff-b7bc4618db15.jpg)
![2](https://user-images.githubusercontent.com/43956964/160533703-ae79890b-a5cf-4ce2-89db-d41b230c8824.jpg)
![3](https://user-images.githubusercontent.com/43956964/160533708-cb5576bc-549d-481f-a0eb-5c1271c39c58.jpg)

**Comment by GJDuck** [comment]
I think I can replicate the bug.  The problem is that the loader is not loading the trampolines, which causes a crash when the program attempts to jump to it.  I will look into a fix.

**Comment by GJDuck** [comment]
It is fixed for me at least, although I only tried a simple program.
