### ISSUE TITLE
Patching Multiple Locations At Once

### ISSUE THREAD

**Issue by chamibuddhika** [GJDuck/e9patch#5]
How can I patch multiple addresses at once?

So far I tried following without success.

```
./e9tool -s --action='addr=0x4392288:call entry@counter, 0x4392336:call entry@counter' redis-server

./e9tool -s --action='addr=0x4392288:call entry@counter' --action='addr=0x4392336:call entry@counter'  redis-server
```

**Comment by GJDuck** [comment]
This one should now work:

    ./e9tool -s --action='addr=0x4392288:call entry@counter' --action='addr=0x4392336:call entry@counter'  redis-server

There was a bug preventing it from working before but that is now fixed.

You can also use regex to match multiple locations:

    ./e9tool -s --action='addr=(0x4392288|0x4392336):call entry@counter' redis-server
