### ISSUE TITLE
freeELF is not in e9tool namespace

### ISSUE THREAD

**Issue by liangjs** [GJDuck/e9patch#57]
The `freeELF` function is not defined in the `e9tool` namespace.
https://github.com/GJDuck/e9patch/blob/855e8b8092f27ec5c3deb1bc1e7b28e50da6800f/src/e9tool/e9frontend.cpp#L1448

This will cause plugins unable to call use this function.
```
undefined symbol: _ZN6e9tool7freeELFEPNS_3ELFE
```

**Comment by GJDuck** [comment]
Thanks for the report.  It is fixed.
