### ISSUE TITLE
std::regex_error on long regex lines

### ISSUE THREAD

**Issue by chamibuddhika** [GJDuck/e9patch#6]
I am getting the following error when I am trying to pass in a long list of addresses (around 950 addresses triggers this error in my case) to `e9tool` via the command line.

```
./e9tool -s --action='addr=(0x430560|0x430590|0x4305a0|0x4305e0|0x430620|........|0x4c5440|0x4c54f0|0x4c5500|0x4c55e0|0x4c55f0|0x4c5750|0x4c5780|0x4c5930|0x4c5c60|0x4c6290|0x4c6450|0x4c649):call entry@counter' -o r redis-server
7995

terminate called after throwing an instance of 'std::regex_error'
  what():  Parenthesis is not closed.                                                                      
Aborted
```

Just to explain what I am trying to achieve here, I want to test two instrumentation tasks.

1. Instrumenting all function entries.
2. Instrumenting all basic blocks entries.

So currently I am getting all function entry and basic block entry addresses from some other tool and feed it to `e9tool` via command line. Please let me know if there is a better way of doing this.

**Comment by GJDuck** [comment]
A student of ours had a similar problem.  Unfortunately, this pushes the limits of the current command line interface.  We intend to redesign it, but that may take some time.

In the meantime, you can try the plugin interface as documented here: [E9Patch Programmer's Guide](https://github.com/GJDuck/e9patch/blob/master/doc/e9patch-programming-guide.md).
It is low-level, but it could be used to implement this kind of application.

**Comment by chamibuddhika** [comment]
I see. I just checked out the API guide. Is there any existing plugin implementation that I may refer to (probably
would make it easier if that's the case)?

**Comment by GJDuck** [comment]
Unfortunately there are no public samples at this time.  These things should be made available in due course, but the tool is still in a state of flux so things might still change or be designed.

**Comment by GJDuck** [comment]
I've added CSV file support, which should be a solution to this issue.  See the commit message for 51c2d91 and other documentation for more information.
