### ISSUE TITLE
How to instrument after function call instruction?

### ISSUE THREAD

**Issue by komorogrov** [GJDuck/e9patch#67]
Hello, thank you very much for your patient help last time.

I met another problem.

Consider the following case, I want to instrument some function calls such as `call malloc` before executing the next instruction to gather some information about the allocated address after the malloc function is executed.

`call malloc 
--> trampoline: a function to collect some information about malloc address
--> next instruction`

However, from the user guide, the patch is placed in the default `before` position, will be executed as instrumentation *before* the matching instruction. For the `after` position, the trampoline will **not** be executed if the matching instruction transfers control flow (i.e., for jumps taken, calls or returns).

I run the following command line.

`./e9tool --trap-all -M 'call and target=&malloc' -P 'after entry()@count' test-state-tracer-v0 -o test-state-tracer-vx`

The final output binary does not work as expected, the trampoline will not be executed just as the user guide said.

And because instructions are matched in reverse order, I can't insert trampoline before the next instruction that matches `call malloc`.

So I would like to ask you for help. Is there any good solution in  this case?

These are some pictures when debugging.

![deb-12](https://github.com/GJDuck/e9patch/assets/30967717/7709c96c-7eba-40d5-9a6a-41b1ffd44d19)

malloc return to main instead of trampoline code.

![deb-13](https://github.com/GJDuck/e9patch/assets/30967717/cf26a5f6-6342-4bca-8c09-f89336e63a82)

Instrument `xor` instruction work as expected.

`./e9tool --trap-all -M 'asm=/xor.*/' -P 'after entry()@count' test-instr-d-v0 -o test-instr-count3`
![deb-8](https://github.com/GJDuck/e9patch/assets/30967717/ed7dabaf-6fe7-4932-b249-18fd42647f92)

**Comment by GJDuck** [comment]
It should be possible to do this by matching the *next* instruction after the call to `malloc`:

        ./e9tool -M 'I[-1].call and I[-1].target=&malloc' -P 'entry()@count' ...

Here, the prefix `I[-1]` prefix refers to the previous instruction relative to the current instruction, so it is saying "_match all instructions where the previous instruction is a call to malloc_".

**Comment by komorogrov** [comment]
I find it really works as you said after debugging.
![deb-14](https://github.com/GJDuck/e9patch/assets/30967717/16bc2881-bacc-449e-9fec-e1f50d8cd9cf)

After I re-read the user guide, I found that the relevant content is mentioned in section 2.4 of the user guide.
Thanks for your patience.
Thanks for your answer, feeling the power of this excellent tool again. I think it's almost as powerful as LLVM Pass.

**Comment by GJDuck** [comment]
> I think it's almost as powerful as LLVM Pass

One of the main motivations behind E9Patch/E9Tool is to avoid having to write LLVM passes.  Especially since E9Patch works on binary code, meaning that it is not necessary to recompile test subjects.
