### ISSUE TITLE
A further question about issue 68.

### ISSUE THREAD

**Issue by komorogrov** [GJDuck/e9patch#69]
Is there any way to finish the work in https://github.com/GJDuck/e9patch/issues/68 in code nor command line?

Using the command line to match may be tedious in some complex situations, and you need to manually enumerate all the possibilities.

It would be much more elegant and convenient if this could be done directly in code.

Is there any way to pass the return value from `e9_plugin_match()` to the call trampoline code function `entry` instead of enumerating all the cases on the command line?

**Comment by komorogrov** [comment]
This may be impossible in terms of the involved structure of e9patch for these two functions work at different stages.

**Comment by GJDuck** [comment]
Yes it is possible, see the answer in #68.
