### ISSUE TITLE
How to trace executed edges among basic blocks

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [GJDuck/e9patch#7]
Hi, thanks for this work. It is great and exciting.

Right now I am trying to trace the execution using e9patch. Specifically, I want to output all executed edges among basic blocks. For example, If we have 
```asm
0x400000: jz 0x600000
0x400006: jmp 0x500000
```
+ When the first conditional jump (@0x400000) is taken, I want to get **0x400000 --> 0x600000**.
+ When the first conditional jump (@0x400000) is not taken, I want to get **0x400000 --> 0x400006** and **0x400006 --> 0x500000**. Note that **0x400000 --> 0x400006** is important here because these two instructions are in different basic blocks.

I know the external control flow edge (from/to library) may not be traced, but it is fine for me. 

Currently, I am using following code
```c
// name: trace.c

static void __low_level_printf(...) {
    // ignored for easy understanding
}

void entry(void *src, void *dst) {
    __low_level_printf("%p --> %p\n", src, dst);
}
```

And I instrumented the binary using following commands
```bash
./e9tool --match 'asm=j.*|ca.*|ret' --action 'call entry(rip, target)@trace' [INFILE] -o [OUTFILE]
```

May I know whether I did the right thing? I am not sure whether above code can trace the jump edge when the conditional jump is not taken (e.g., **0x400000 --> 0x400006**).

I would very appreciate it if you can help me figure this out. Thanks.

**Comment by GJDuck** [comment]
For this you can use the `next` parameter instead of `target`:

* `target` is the jump/call/return target address, regardless of whether the branch is taken (e.g., for `jcc`).
* `next` is the address of the next instruction executed.  Thus, `next=target` if branch taken, else `next=(rip+instr.size)`.

The main problem with tracing control flow with E9Patch is the coverage for the single-byte `ret` instruction might be poor.

**Comment by ZhangZhuoSJTU** [comment]
@GJDuck Thanks for your prompt reply. It is really helpful.

But I guess it may be good to change the explanation of `next` argument in the [programing guidance](https://github.com/GJDuck/e9patch/blob/master/doc/e9patch-programming-guide.md).  The sentence, "next is the address of the next instruction" is kind of confusing for me. I originally thought the `next` means the next instruction in the __static__ term, which is always equal to`rip + instr.size`. Something like _the next instruction executed_ might be better.

Thanks again.

**Comment by GJDuck** [comment]
The documentation is not very good.  Writing a proper user's guide is still on my TODO list.
