### ISSUE TITLE
[question] How to replace instruction if I only know the binary code of both instructions?

### ISSUE THREAD

**Issue by heagoo** [GJDuck/e9patch#71]
I need to replace instruction_1 to instruction_2, I know the binary code of both instructions. What's the command should I use? Thank you!

**Comment by GJDuck** [comment]
You should be able to match the binary code using `bytes[i]`, e.g.:

        $ ./e9tool -M 'bytes[0] == 0x0F && bytes[1] == 0x0B' -P ...

Replacing instructions between other instructions is not really supported via the command-line interface.  For something like this, you may need to use an E9Tool plugin.

**Comment by GJDuck** [comment]
Closed as answered.
