### ISSUE TITLE
examples on lowfat

### ISSUE THREAD

**Issue by StanPlatinum** [GJDuck/e9patch#8]
Brilliant work!

Do you mind sharing some examples of how to implement low fat pointer instrumentation, using e9patch? Since doing it at binary level that does not need source code is really useful.

Thanks.

**Comment by GJDuck** [comment]
The current version of e9patch still needs some additional features to implement binary LowFat easily (i.e., without RPC calls and machine code manipulation).   But we are working on it and a version will be released eventually.

**Comment by GJDuck** [comment]
[UPDATE] An advanced implementation of low-fat pointer instrumentation using E9Patch has now been released: 

* https://github.com/GJDuck/RedFat

**Comment by StanPlatinum** [comment]
Thanks! I am @mxz297 who's also interested in this.
