### ISSUE TITLE
Installing example/stdlib.c 

### ISSUE THREAD

**Issue by McSinyx** [GJDuck/e9patch#82]
Since it's useful to the users, I suggest installing it under `$PREFIX/include/e9patch/stdlib.h`, possibly with `struct STATE` split into `$PREFIX/include/e9patch/state.h`.

**Comment by GJDuck** [comment]
It is current installed under `$(DESTDIR)/usr/share/e9compile/include/stdlib.c`, and that path should already be searched by `e9compile`.  Let me know if it is not working.

The `STATE` was originally a separate file, but then it was later consolidated into `stdlib.c`.

**Comment by McSinyx** [comment]
Thank you for the information, that should be working on most distros, but on non FHS systems like Guix and NixOS, `/usr` cannot be assumed as the prefix.  I will try to send out a patch for that.
