### ISSUE TITLE
Installing headers to standard location

### ISSUE THREAD

**Issue by McSinyx** [GJDuck/e9patch#98]
This is a generalization of GH-82.  If I understand correctly, the following headers/source files are part of the API:

examples/stdlib.c and src/e9patch/e9loader.h are to be used by call trampolines.  Hard-coding their path in e9compile (the only place they are documented to be used) during build time is, although complicated, compliant with FHS, as /usr/share is for application data (data used by e9compile).

src/e9tool/e9tool.h and src/e9tool/e9plugin.h are to be used by the plugin API.  These are **not** used by any E9 program (e9patch, e9tool or e9compile) but in build process of third-party software.  IMHO having to pass `-I/usr/share/e9tool/include` to the compiler is the reverse of the justifiable abstraction in the previous case, i.e. neither justifiable (not FHS-compliant) nor abstract (requiring specifying an explicit include path).

I strongly suggest installing the latter two inside $PREFIX/include/e9tool (e.g. /usr/include/e9tool).  Edit: patch included.

**Comment by GJDuck** [comment]
Yes, this is a good idea.
